MakeAmazingThings/MakeAmazingThings/Models/Produtos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MakeAmazingThings.Models
{
    public class Produtos
    {   
        //construtor
        public Produtos()
        {
            ListaDeCompras = new HashSet<DescricaoCompra>();

            
        }
        
        [Key]
        public int ID { get; set; }


        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório!")]
        public string Marca { get; set; }

        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório!")]
        [Display(Name = "Nome do Produto")]
        public string NomeProd { get; set; }

        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório!")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório!")]
        [Display(Name = "Publico Alvo")]
        public string SexoDoUtilizador { get; set; }
        
        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório!")]
        [Display(Name = "Stock Disponivel")]
        public int Stock { get; set; }

        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório!")]
        [Display(Name = "Preço")]
        public decimal Preco { get; set; }

        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório!")]
        public decimal IvaVenda { get; set; }

        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório!")]
        public bool Ativo { get; set; }  // situacao do produto

        public string Fotografia { get; set; }




        //************************************************************************************************
        // referência às fotografias associadas a um Produto
        public virtual ICollection<DescricaoCompra> ListaDeCompras { get; set; }

    }
}

MakeAmazingThings/MakeAmazingThings/Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IdentitySample.Models;
using MakeAmazingThings.Models;

namespace MakeAmazingThings.Controllers
{
    public class ProdutosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Produtos
        // [ValidateAntiForgeryToken]
        public ActionResult Index(string btPesquisa)
        {
            // guarda a lista de produtos a serem apresentados, no ecrã, ao utilizador
            List<Produtos> listaProdutos = new List<Produtos>();

            if (!String.IsNullOrEmpty(btPesquisa) && !btPesquisa.Equals("Todos"))
            {
                // mostra apenas os produtos 'masculino', 'feminino' ou 'unisexo',
                // conforme a escolha do utilizador
                listaProdutos = db.Produtos.Where(p => p.SexoDoUtilizador.Equals(btPesquisa)).OrderByDescending(p => p.Ativo).ToList();
            }
            else
            {
                // não há filtragem de produtos
                listaProdutos = db.Produtos.OrderByDescending(p => p.Ativo).ToList();
            }

            //funcçao do where define se 
            return View(listaProdutos);
        }

        // GET: Produtos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produtos produtos = db.Produtos.Find(id);
            if (produtos == null)
            {
                return HttpNotFound();
            }
            return View(produtos);
        }

        // GET: Produtos/Create
        public ActionResult Create()
        {

            var listaDeOpcoes = new SelectList(new List<SelectListItem> {
                new SelectListItem { Text = "Unisexo", Value = "Unisexo"},
                new SelectListItem { Text = "Masculino", Value ="Masculino"},
                new SelectListItem { Text = "Feminino", Value = "Feminino"}
            }, "Text", "Value");

            ViewBag.SexoDoUtilizador = listaDeOpcoes;

            return View();
        }

        // POST: Produtos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Marca,NomeProd,Descricao,SexoDoUtilizador,Stock,Preco,IvaVenda,Ativo,Fotografia")] Produtos produto, HttpPostedFileBase fileUploadFotografia)
        {
            // determinar o ID do novo Agente
            int novoID = 0;
            // *****************************************
            // proteger a geração de um novo ID
            // *****************************************
            // determinar o nº de Agentes na tabela
            if (db.Produtos.Count() == 0)
            {
                novoID = 1;
            }
            else
            {
                novoID = db.Produtos.Max(a => a.ID) + 1;
            }
            // atribuir o ID ao novo agente
            produto.ID = novoID;
            // ***************************************************
            // outra hipótese possível seria utilizar o
            // try { }
            // catch(Exception) { }
            // ***************************************************


            // var. auxiliar
            string nomeFotografia = "Produto_" + novoID + ".jpg";
            string caminhoParaFotografia = Path.Combine(Server.MapPath("~/imagens/"), nomeFotografia); // indica onde a imagem será guardada

            // verificar se chega efetivamente um ficheiro ao servidor
            if (fileUploadFotografia != null)
            {
                // guardar o nome da imagem na BD
                produto.Fotografia = nomeFotografia;
            }
            else
            {
                // não há imagem...
                ModelState.AddModelError("", "Não foi fornecida uma imagem..."); // gera MSG de erro
                return View(produto); // reenvia os dados do 'Agente' para a View
            }

            // avaliar se foi escolhido um tipo de público alvo
            // se não escolhi, devolver o objeto à view

            if (ModelState.IsValid)
            {
                try
                {
                    // adiciona na estrutura de dados, na memória do servidor,
                    // o objeto Agentes
                    db.Produtos.Add(produto);
                    // faz 'commit' na BD
                    db.SaveChanges();

                    // guardar a imagem no disco rígido
                    fileUploadFotografia.SaveAs(caminhoParaFotografia);

                    // redireciona o utilizador para a página de início
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    // gerar uma mensagem de erro para o utilizador
                    ModelState.AddModelError("", "Ocorreu um erro não determinado na criação do novo Agente...");
                }
            }
            

            var listaDeOpcoes = new SelectList(new List<SelectListItem> {
                new SelectListItem { Text = "Unisexo", Value = "Unisexo"},
                new SelectListItem { Text = "Masculino", Value ="Masculino"},
                new SelectListItem { Text = "Feminino", Value = "Feminino"}
            }, "Text", "Value", produto.SexoDoUtilizador);

            ViewBag.SexoDoUtilizador = listaDeOpcoes;

            return View(produto);
        }

        // GET: Produtos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
             var listaDeOpcoes = new SelectList(new List<SelectListItem> {
                new SelectListItem { Text = "Unisexo", Value = "Unisexo"},
                new SelectListItem { Text = "Masculino", Value ="Masculino"},
                new SelectListItem { Text = "Feminino", Value = "Feminino"}
            }, "Text", "Value");

            ViewBag.SexoDoUtilizador = listaDeOpcoes;
            
            Produtos produtos = db.Produtos.Find(id);
            if (produtos == null)
            {
                return HttpNotFound();
            }
            return View(produtos);
        }

        // POST: Produtos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Marca,NomeProd,Descricao,SexoDoUtilizador,Stock,Preco,IvaVenda,Ativo,Fotografia")] Produtos produtos, HttpPostedFileBase fileUploadFotografia)
        {

            // var. auxiliar
            string nomeFotografia = "Produto_" + produtos.ID + ".jpg";
            string caminhoParaFotografia = Path.Combine(Server.MapPath("~/imagens/"), nomeFotografia); // indica onde a imagem será guardada

            // verificar se chega efetivamente um ficheiro ao servidor
            if (fileUploadFotografia != null)
            {
                // guardar o nome da imagem na BD
                produtos.Fotografia = nomeFotografia;
            }
            else
            {
                // não há imagem...
                ModelState.AddModelError("", "Não foi fornecida uma imagem..."); // gera MSG de erro
                return View(produtos); // reenvia os dados do 'Agente' para a View
            }

            // avaliar se foi escolhido um tipo de público alvo
            // se não escolhi, devolver o objeto à view

            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(produtos).State = EntityState.Modified;
                  
                    // faz 'commit' na BD
                    db.SaveChanges();

                    // guardar a imagem no disco rígido
                    fileUploadFotografia.SaveAs(caminhoParaFotografia);

                    // redireciona o utilizador para a página de início
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    // gerar uma mensagem de erro para o utilizador
                    ModelState.AddModelError("", "Ocorreu um erro não determinado na criação do novo Agente...");
                }
            }

            var listaDeOpcoes = new SelectList(new List<SelectListItem> {
                new SelectListItem { Text = "Unisexo", Value = "Unisexo"},
                new SelectListItem { Text = "Masculino", Value ="Masculino"},
                new SelectListItem { Text = "Feminino", Value = "Feminino"}
            }, "Text", "Value", produtos.SexoDoUtilizador);

            ViewBag.SexoDoUtilizador = listaDeOpcoes;
            //return View(produtos);
            return RedirectToAction("Index");
        }

        // GET: Produtos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produtos produtos = db.Produtos.Find(id);
            if (produtos == null)
            {
                return HttpNotFound();
            }
            return View(produtos);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produtos produtos = db.Produtos.Find(id);
            db.Produtos.Remove(produtos);

MakeAmazingThings/MakeAmazingThings/Views/Produtos/Create.cshtml
@model MakeAmazingThings.Models.Produtos
@{
    ViewBag.Title = "Create";
}
<h2>Create</h2>

@using (Html.BeginForm("Create",
                      "Produtos",
                      FormMethod.Post,
                      new { enctype = "multipart/form-data" }
                      ))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Produtos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*Adicionar escolha de Marca*@
        <div class="form-group">
            @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
            </div>
        </div>
        @***********************************@

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomeProd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeProd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeProd, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>
        @* ***************************** Adicionar escolha de Publico Alvo ************************************************************* *@
        <div class="form-group">
            @Html.LabelFor(model => model.SexoDoUtilizador, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SexoDoUtilizador", null, "Escolha o público alvo do produto", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SexoDoUtilizador, "", new { @class = "text-danger" })
            </div>
        </div>
        @* **************************************************************************************************************************** *@
        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IvaVenda, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IvaVenda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IvaVenda, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
    @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @*@Html.EditorFor(model => model.Fotografia, new { htmlAttributes = new { @class = "form-control" } })*@

        @* File Upload *@
        <input type="file"
               name="fileUploadFotografia"
               style="color:blue;"
               accept=".jpg" />

        @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
    </div>
</div>


        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MakeAmazingThings/MakeAmazingThings/Views/Produtos/Delete.cshtml
@model MakeAmazingThings.Models.Produtos

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produtos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NomeProd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NomeProd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IvaVenda)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IvaVenda)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MakeAmazingThings/MakeAmazingThings/Views/Produtos/Details.cshtml
@model MakeAmazingThings.Models.Produtos
@{
    ViewBag.Title = "Details";
}
@*TEM DE ADICIONAR O CODIGO DA ESCOLHA DO PUBLICO ALVO COMO NO CREATE*@
<h2>Details</h2>
<div>
    <h4>Produtos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NomeProd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NomeProd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Stock)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Stock)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IvaVenda)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IvaVenda)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fotografia)
        </dt>
        <dd>
            <a href="~/imagens/Produtos" target="_blank">
                <img src="~/imagens/@Model.Fotografia" class="img-responsive" style="width:25%" />
            </a>
        </dd>

    </dl>
</div>
@if (User.IsInRole("Administrador"))
{
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) </p>
}
<p>
        @Html.ActionLink("Back to List", "Index")
    </p>

MakeAmazingThings/MakeAmazingThings/Views/Produtos/Edit.cshtml
@model MakeAmazingThings.Models.Produtos
@{
    ViewBag.Title = "Edit";
}
<h2>Edit</h2>
@using (Html.BeginForm("Edit",
                      "Produtos",
                      FormMethod.Post,
                      new { enctype = "multipart/form-data" }
                      ))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Produtos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NomeProd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeProd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeProd, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SexoDoUtilizador, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SexoDoUtilizador", null, "Escolha o público alvo do produto", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SexoDoUtilizador, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IvaVenda, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IvaVenda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IvaVenda, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Fotografia, new { htmlAttributes = new { @class = "form-control" } })*@

                @* File Upload *@
                <input type="file"
                       name="fileUploadFotografia"
                       style="color:blue;"
                       accept=".jpg" />

                @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MakeAmazingThings/MakeAmazingThings/Views/Produtos/Index.cshtml
@model IEnumerable<MakeAmazingThings.Models.Produtos>

@{
    ViewBag.Title = "Produtos-MAT";
}

<h2>Lista de Produtos</h2>

@if (User.IsInRole("Administrador")) {
    <p>
    @Html.ActionLink("Adicionar novo produto", "Create")
</p>
}
    

@using (Html.BeginForm())
{
    <div>
        <input type="submit" name="btPesquisa" value="Unisexo" />
        <input type="submit" name="btPesquisa" value="Masculino" />
        <input type="submit" name="btPesquisa" value="Feminino" />
        <input type="submit" name="btPesquisa" value="Todos" />
    </div>
}

    <div class="row" >
        @foreach (var item in Model)
    {

        <div class="col-sm-3" style="padding:4px 4px 4px 4px">

            <a href="@Url.Action("Details","Produtos", new { id=item.ID } )">
                <img src="~/imagens/@item.Fotografia" class="img-responsive" style="width:75%" />
            </a>
            <p> @Html.DisplayFor(modelItem => item.Marca)</p>
            <p> @Html.DisplayFor(modelItem => item.NomeProd)</p>
            <p> @Html.DisplayFor(modelItem => item.Preco)€</p>

            @if (User.IsInRole("Administrador")) {<p>
    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
</p> }
        

        </div>
}
    </div>





        @*
            }
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Marca)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.NomeProd)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Descricao)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Stock)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Preco)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IvaVenda)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Ativo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SexoDoUtilizador)
                        </th>

                        <th></th>
                    </tr>





                    @foreach (var item in Model)
                {

                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Marca)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NomeProd)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Descricao)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Stock)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Preco)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IvaVenda)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ativo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SexoDoUtilizador)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                            @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                        </td>
                    </tr>

            }

                </table>

        *@